[package]
name = "twilight"
version = "0.1.0"
authors = ["Twilight and Serenity Contributors"]
edition = "2021"

[dependencies]
futures = "0.3"
reqwest = "0.11"
tracing = "0.1"
tracing-subscriber = "0.2"
tokio = { features = ["macros", "rt-multi-thread", "sync"], version = "1" }
twilight-gateway = "0.8"
twilight-http = "0.8"
twilight-model = "0.8"
twilight-standby = "0.8"

[dependencies.songbird]
default-features = false
path = "../.."
features = ["driver", "twilight-rustls", "zlib-stock"]

[dependencies.symphonia]
# version = "0.4"
git = "https://github.com/pdeljanov/Symphonia"
features = ["aac", "mp3", "isomp4", "alac"]
